fix an issue in promnesia server after pydantic 2.0 update (fastapi dependency)
the `Url = str` alias was causing

    AttributeError: 'pydantic_core._pydantic_core.Url' object has no attribute 'strip'

possibly several issues here

- `Url` is some sort of builtin pydantic primitive
- if you rename it to another name (e.g. `Url2`), we get some weird forward reference error

don't have energy to investigate this now, so just use str instead for now